<a href="https://colab.research.google.com/github/Gustateclogia/AT01-An-lise-Explorat-ria-Tempo/blob/main/Gustavo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Luis Gustavo - Enzo Alzaga - Tiago Antônio - David Silva - Antônio Falcão - Samantha Cavalcanti - Marcelo Tec de informática - 3 Mod - Noite

In [17]:
import pandas as pd
import statistics as st
import seaborn as se

In [18]:
tempo = pd.read_csv('/content/drive/MyDrive/arquivo/tempo.csv', sep=',')

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
tempo

   Aparencia  Temperatura  Umidade       Vento Jogar
0        sol           85     85.0       FALSO   nao
1        sol           80     90.0  VERDADEIRO   nao
2    nublado           83     86.0       FALSO   sim
3      chuva           70      NaN       FALSO   sim
4      chuva           68     80.0       FALSO   sim
5      chuva           65     70.0  VERDADEIRO   nao
6      menos           64     65.0  VERDADEIRO   sim
7        sol         1220     95.0       FALSO   nao
8        sol           69     70.0       FALSO   sim
9      chuva           75    200.0         NaN   sim
10       sol           75     70.0  VERDADEIRO   sim
11   nublado           72     90.0  VERDADEIRO   sim
12   nublado           81     75.0       FALSO   sim
13     chuva           71     91.0  VERDADEIRO   nao

In [21]:
tempo
tempo.head(8)
tempo.tail(5)
tempo.sample(7)

   Aparencia  Temperatura  Umidade       Vento Jogar
6      menos           64     65.0  VERDADEIRO   sim
10       sol           75     70.0  VERDADEIRO   sim
13     chuva           71     91.0  VERDADEIRO   nao
11   nublado           72     90.0  VERDADEIRO   sim
2    nublado           83     86.0       FALSO   sim
9      chuva           75    200.0         NaN   sim
1        sol           80     90.0  VERDADEIRO   nao

In [22]:
aparencia = tempo.groupby(['Aparencia']).size()
aparencia

Aparencia
chuva      5
menos      1
nublado    3
sol        5
dtype: int64

In [23]:
Temperatura = tempo.groupby(['Temperatura']).size()
Temperatura

Temperatura
64      1
65      1
68      1
69      1
70      1
71      1
72      1
75      2
80      1
81      1
83      1
85      1
1220    1
dtype: int64

In [24]:
Umidade = tempo.groupby(['Umidade']).size()
Umidade

Umidade
65.0     1
70.0     3
75.0     1
80.0     1
85.0     1
86.0     1
90.0     2
91.0     1
95.0     1
200.0    1
dtype: int64

In [25]:
Vento = tempo.groupby(['Vento']).size()
Vento

Vento
FALSO         7
VERDADEIRO    6
dtype: int64

In [26]:
Jogar = tempo.groupby(['Jogar']).size()
Jogar

Jogar
nao    5
sim    9
dtype: int64

In [28]:
tempo.loc[tempo['Aparencia'] == 'menos', 'Aparencia'] = 'sol'

In [29]:
mediana_temp = tempo['Temperatura'].median() # Nota: ideal calcular a mediana sem o outlier
tempo.loc[tempo['Temperatura'] > 130, 'Temperatura'] = mediana_temp

/tmp/ipykernel_7595/2662572036.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '73.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tempo.loc[tempo['Temperatura'] > 130, 'Temperatura'] = mediana_temp

In [30]:
mediana_umid = tempo['Umidade'].median()
tempo['Umidade'].fillna(mediana_umid, inplace=True)
tempo.loc[(tempo['Umidade'] < 0) | (tempo['Umidade'] > 100), 'Umidade'] = mediana_umid

/tmp/ipykernel_7595/1362220565.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tempo['Umidade'].fillna(mediana_umid, inplace=True)

In [31]:
tempo['Vento'].fillna('FALSO', inplace=True)

/tmp/ipykernel_7595/2896138193.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tempo['Vento'].fillna('FALSO', inplace=True)